
cursor #dedede
foreground #c4c6d0
background #141416
selection_foreground #dedede
selection_background #363638
# Black
color0  #161717
color8  #181819
# Red
color1  #df5b61
color9  #ee6a70
# Green
color2  #87c7a1
color10 #96d6b0
# Yellow
color3  #de8f78
color11 #ffb29b
# Blue
color4  #6791c9
color12 #7ba5dd
# Magenta
color5  #aca1cf
color13 #b9aeda
# Cyan
# color6  #ce9276
# color14 #ffb592
color6  #70b9cc
color14 #7fc8db
# White
color7  #c4c4c4
color15 #cccccc

active_tab_foreground   #161717
active_tab_background   #de8f78
inactive_tab_foreground #c4c4c4
inactive_tab_background #252528

active_border_color   #545654
inactive_border_color #2a2a2d
inactive_text_alpha   1.0
